

#spring:
#  aop:
#    auto: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/xqglxt?useUnicode=true&characterEncoding=utf8&useSSL=false

server:
  port: 8089
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    jdbc-type-for-null: null
    map-underscore-to-camel-case: false


logging:
  config: classpath:log4j2-spring.xml
#  level:
#    cn.wy.bs.mapper: debug

spring:
#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
  aop:
    auto: true
  datasource:
#    primary:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/xqglxt?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      username: root
      password: 123456
      validation-query: 'SELECT 1 FROM T_USER'
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      max-active: 20
      min-idle: 5
      initial-size: 5
      time-between-eviction-runs-millis: 3600000
#    shiro:
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      druid:
#        username: root
#        password: 123456
#        validation-query: 'SELECT 1 FROM T_USER'
#        test-on-borrow: true
#        test-on-return: false
#        test-while-idle: true
#        max-active: 20
#        min-idle: 5
#        initial-size: 5
#        time-between-eviction-runs-millis: 3600000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 1
    timeout: 0










